// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_20.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	game_20.proto
	user_10.proto

It has these top-level messages:
	RoomBriefInfo
	C2S_GetRoomList_20000
	S2C_GetRoomList_20000
	C2S_CreateRoom_20001
	S2C_CreateRoom_20001
	C2S_JoinRoom_20002
	S2C_JoinRoom_20002
	C2S_LeaveRoom_20003
	S2C_LeaveRoom_20003
	MailRequest
	MailResponse
	Player_Info
	C2S_Login_10001
	S2C_Login_10001
	C2S_SetNick_10002
	S2C_SetNick_10002
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoomBriefInfo struct {
	RoomId    int32 `protobuf:"varint,1,opt,name=roomId" json:"roomId,omitempty"`
	PlayerNum int32 `protobuf:"varint,2,opt,name=playerNum" json:"playerNum,omitempty"`
}

func (m *RoomBriefInfo) Reset()                    { *m = RoomBriefInfo{} }
func (m *RoomBriefInfo) String() string            { return proto.CompactTextString(m) }
func (*RoomBriefInfo) ProtoMessage()               {}
func (*RoomBriefInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RoomBriefInfo) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomBriefInfo) GetPlayerNum() int32 {
	if m != nil {
		return m.PlayerNum
	}
	return 0
}

type C2S_GetRoomList_20000 struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *C2S_GetRoomList_20000) Reset()                    { *m = C2S_GetRoomList_20000{} }
func (m *C2S_GetRoomList_20000) String() string            { return proto.CompactTextString(m) }
func (*C2S_GetRoomList_20000) ProtoMessage()               {}
func (*C2S_GetRoomList_20000) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *C2S_GetRoomList_20000) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type S2C_GetRoomList_20000 struct {
	Ret  int32            `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	Room []*RoomBriefInfo `protobuf:"bytes,2,rep,name=room" json:"room,omitempty"`
}

func (m *S2C_GetRoomList_20000) Reset()                    { *m = S2C_GetRoomList_20000{} }
func (m *S2C_GetRoomList_20000) String() string            { return proto.CompactTextString(m) }
func (*S2C_GetRoomList_20000) ProtoMessage()               {}
func (*S2C_GetRoomList_20000) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *S2C_GetRoomList_20000) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *S2C_GetRoomList_20000) GetRoom() []*RoomBriefInfo {
	if m != nil {
		return m.Room
	}
	return nil
}

type C2S_CreateRoom_20001 struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *C2S_CreateRoom_20001) Reset()                    { *m = C2S_CreateRoom_20001{} }
func (m *C2S_CreateRoom_20001) String() string            { return proto.CompactTextString(m) }
func (*C2S_CreateRoom_20001) ProtoMessage()               {}
func (*C2S_CreateRoom_20001) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *C2S_CreateRoom_20001) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type S2C_CreateRoom_20001 struct {
	Ret    int32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	RoomId int32 `protobuf:"varint,2,opt,name=roomId" json:"roomId,omitempty"`
}

func (m *S2C_CreateRoom_20001) Reset()                    { *m = S2C_CreateRoom_20001{} }
func (m *S2C_CreateRoom_20001) String() string            { return proto.CompactTextString(m) }
func (*S2C_CreateRoom_20001) ProtoMessage()               {}
func (*S2C_CreateRoom_20001) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *S2C_CreateRoom_20001) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *S2C_CreateRoom_20001) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type C2S_JoinRoom_20002 struct {
	Uid    int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	RoomId int32 `protobuf:"varint,2,opt,name=roomId" json:"roomId,omitempty"`
}

func (m *C2S_JoinRoom_20002) Reset()                    { *m = C2S_JoinRoom_20002{} }
func (m *C2S_JoinRoom_20002) String() string            { return proto.CompactTextString(m) }
func (*C2S_JoinRoom_20002) ProtoMessage()               {}
func (*C2S_JoinRoom_20002) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *C2S_JoinRoom_20002) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *C2S_JoinRoom_20002) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type S2C_JoinRoom_20002 struct {
	Ret    int32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	RoomId int32 `protobuf:"varint,2,opt,name=roomId" json:"roomId,omitempty"`
}

func (m *S2C_JoinRoom_20002) Reset()                    { *m = S2C_JoinRoom_20002{} }
func (m *S2C_JoinRoom_20002) String() string            { return proto.CompactTextString(m) }
func (*S2C_JoinRoom_20002) ProtoMessage()               {}
func (*S2C_JoinRoom_20002) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *S2C_JoinRoom_20002) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *S2C_JoinRoom_20002) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type C2S_LeaveRoom_20003 struct {
	Uid    int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	RoomId int32 `protobuf:"varint,2,opt,name=roomId" json:"roomId,omitempty"`
}

func (m *C2S_LeaveRoom_20003) Reset()                    { *m = C2S_LeaveRoom_20003{} }
func (m *C2S_LeaveRoom_20003) String() string            { return proto.CompactTextString(m) }
func (*C2S_LeaveRoom_20003) ProtoMessage()               {}
func (*C2S_LeaveRoom_20003) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *C2S_LeaveRoom_20003) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *C2S_LeaveRoom_20003) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type S2C_LeaveRoom_20003 struct {
	Ret int32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
}

func (m *S2C_LeaveRoom_20003) Reset()                    { *m = S2C_LeaveRoom_20003{} }
func (m *S2C_LeaveRoom_20003) String() string            { return proto.CompactTextString(m) }
func (*S2C_LeaveRoom_20003) ProtoMessage()               {}
func (*S2C_LeaveRoom_20003) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *S2C_LeaveRoom_20003) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

// 请求消息
type MailRequest struct {
	Mail string `protobuf:"bytes,1,opt,name=Mail" json:"Mail,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=Text" json:"Text,omitempty"`
}

func (m *MailRequest) Reset()                    { *m = MailRequest{} }
func (m *MailRequest) String() string            { return proto.CompactTextString(m) }
func (*MailRequest) ProtoMessage()               {}
func (*MailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MailRequest) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *MailRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// 响应消息
type MailResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=Ok" json:"Ok,omitempty"`
}

func (m *MailResponse) Reset()                    { *m = MailResponse{} }
func (m *MailResponse) String() string            { return proto.CompactTextString(m) }
func (*MailResponse) ProtoMessage()               {}
func (*MailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MailResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*RoomBriefInfo)(nil), "protos.RoomBriefInfo")
	proto.RegisterType((*C2S_GetRoomList_20000)(nil), "protos.C2S_GetRoomList_20000")
	proto.RegisterType((*S2C_GetRoomList_20000)(nil), "protos.S2C_GetRoomList_20000")
	proto.RegisterType((*C2S_CreateRoom_20001)(nil), "protos.C2S_CreateRoom_20001")
	proto.RegisterType((*S2C_CreateRoom_20001)(nil), "protos.S2C_CreateRoom_20001")
	proto.RegisterType((*C2S_JoinRoom_20002)(nil), "protos.C2S_JoinRoom_20002")
	proto.RegisterType((*S2C_JoinRoom_20002)(nil), "protos.S2C_JoinRoom_20002")
	proto.RegisterType((*C2S_LeaveRoom_20003)(nil), "protos.C2S_LeaveRoom_20003")
	proto.RegisterType((*S2C_LeaveRoom_20003)(nil), "protos.S2C_LeaveRoom_20003")
	proto.RegisterType((*MailRequest)(nil), "protos.MailRequest")
	proto.RegisterType((*MailResponse)(nil), "protos.MailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GameService service

type GameServiceClient interface {
	SendMail(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (*MailResponse, error)
	GetRoomList(ctx context.Context, in *C2S_GetRoomList_20000, opts ...grpc.CallOption) (*S2C_GetRoomList_20000, error)
	CreateRoom(ctx context.Context, in *C2S_CreateRoom_20001, opts ...grpc.CallOption) (*S2C_CreateRoom_20001, error)
	JoinRoom(ctx context.Context, in *C2S_JoinRoom_20002, opts ...grpc.CallOption) (*S2C_JoinRoom_20002, error)
	LeaveRoom(ctx context.Context, in *C2S_LeaveRoom_20003, opts ...grpc.CallOption) (*S2C_LeaveRoom_20003, error)
}

type gameServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameServiceClient(cc *grpc.ClientConn) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) SendMail(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (*MailResponse, error) {
	out := new(MailResponse)
	err := grpc.Invoke(ctx, "/protos.GameService/SendMail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetRoomList(ctx context.Context, in *C2S_GetRoomList_20000, opts ...grpc.CallOption) (*S2C_GetRoomList_20000, error) {
	out := new(S2C_GetRoomList_20000)
	err := grpc.Invoke(ctx, "/protos.GameService/GetRoomList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) CreateRoom(ctx context.Context, in *C2S_CreateRoom_20001, opts ...grpc.CallOption) (*S2C_CreateRoom_20001, error) {
	out := new(S2C_CreateRoom_20001)
	err := grpc.Invoke(ctx, "/protos.GameService/CreateRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) JoinRoom(ctx context.Context, in *C2S_JoinRoom_20002, opts ...grpc.CallOption) (*S2C_JoinRoom_20002, error) {
	out := new(S2C_JoinRoom_20002)
	err := grpc.Invoke(ctx, "/protos.GameService/JoinRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) LeaveRoom(ctx context.Context, in *C2S_LeaveRoom_20003, opts ...grpc.CallOption) (*S2C_LeaveRoom_20003, error) {
	out := new(S2C_LeaveRoom_20003)
	err := grpc.Invoke(ctx, "/protos.GameService/LeaveRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GameService service

type GameServiceServer interface {
	SendMail(context.Context, *MailRequest) (*MailResponse, error)
	GetRoomList(context.Context, *C2S_GetRoomList_20000) (*S2C_GetRoomList_20000, error)
	CreateRoom(context.Context, *C2S_CreateRoom_20001) (*S2C_CreateRoom_20001, error)
	JoinRoom(context.Context, *C2S_JoinRoom_20002) (*S2C_JoinRoom_20002, error)
	LeaveRoom(context.Context, *C2S_LeaveRoom_20003) (*S2C_LeaveRoom_20003, error)
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GameService/SendMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).SendMail(ctx, req.(*MailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetRoomList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2S_GetRoomList_20000)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetRoomList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GameService/GetRoomList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetRoomList(ctx, req.(*C2S_GetRoomList_20000))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2S_CreateRoom_20001)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GameService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateRoom(ctx, req.(*C2S_CreateRoom_20001))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2S_JoinRoom_20002)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GameService/JoinRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).JoinRoom(ctx, req.(*C2S_JoinRoom_20002))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_LeaveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2S_LeaveRoom_20003)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).LeaveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GameService/LeaveRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).LeaveRoom(ctx, req.(*C2S_LeaveRoom_20003))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMail",
			Handler:    _GameService_SendMail_Handler,
		},
		{
			MethodName: "GetRoomList",
			Handler:    _GameService_GetRoomList_Handler,
		},
		{
			MethodName: "CreateRoom",
			Handler:    _GameService_CreateRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _GameService_JoinRoom_Handler,
		},
		{
			MethodName: "LeaveRoom",
			Handler:    _GameService_LeaveRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game_20.proto",
}

func init() { proto.RegisterFile("game_20.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x51, 0x8f, 0xd2, 0x40,
	0x10, 0xc7, 0x7b, 0xe5, 0xbc, 0xd0, 0xa9, 0x67, 0xcc, 0x00, 0x86, 0xf4, 0xd0, 0x5c, 0xf6, 0x45,
	0xee, 0xe5, 0x52, 0x7b, 0x31, 0xbe, 0xa9, 0x11, 0x0d, 0x81, 0x80, 0x24, 0x5b, 0xde, 0x49, 0x95,
	0xc1, 0x34, 0xd0, 0x2e, 0xb6, 0x85, 0xe8, 0xb7, 0xf6, 0x23, 0x98, 0xdd, 0x02, 0xdd, 0x96, 0xc6,
	0x78, 0x4f, 0xcc, 0xee, 0xcc, 0xfc, 0xfe, 0x7f, 0x76, 0xa6, 0x70, 0xfd, 0x23, 0x88, 0x68, 0xe1,
	0xb9, 0xf7, 0xdb, 0x44, 0x64, 0x02, 0xaf, 0xd4, 0x4f, 0xca, 0xbe, 0xc0, 0x35, 0x17, 0x22, 0xfa,
	0x94, 0x84, 0xb4, 0x1a, 0xc5, 0x2b, 0x81, 0x2f, 0xe0, 0x2a, 0x11, 0x22, 0x1a, 0x2d, 0xbb, 0x17,
	0xb7, 0x17, 0xfd, 0x27, 0xfc, 0x70, 0xc2, 0x1e, 0x58, 0xdb, 0x4d, 0xf0, 0x9b, 0x92, 0xaf, 0xbb,
	0xa8, 0x6b, 0xaa, 0x54, 0x71, 0xc1, 0xee, 0xa0, 0x33, 0xf0, 0xfc, 0xc5, 0x90, 0x32, 0x49, 0x9b,
	0x84, 0x69, 0xb6, 0xf0, 0x5c, 0xd7, 0x75, 0xf1, 0x39, 0x34, 0x76, 0x61, 0xce, 0x6a, 0x70, 0x19,
	0xb2, 0x39, 0x74, 0x7c, 0x6f, 0x50, 0x5f, 0x9a, 0x50, 0x76, 0x90, 0x95, 0x21, 0xde, 0xc1, 0xa5,
	0x54, 0xef, 0x9a, 0xb7, 0x8d, 0xbe, 0xed, 0x75, 0x72, 0xeb, 0xe9, 0x7d, 0xc9, 0x30, 0x57, 0x25,
	0xac, 0x0f, 0x6d, 0x69, 0x60, 0x90, 0x50, 0x90, 0x91, 0x2c, 0x50, 0xd0, 0x37, 0x35, 0xfa, 0x1f,
	0xa1, 0x2d, 0xf5, 0xeb, 0x2a, 0x2b, 0xf2, 0xc5, 0x53, 0x98, 0xfa, 0x53, 0xb0, 0xf7, 0x80, 0x52,
	0x6b, 0x2c, 0xc2, 0xf8, 0xd4, 0xef, 0x9d, 0x2b, 0xfd, 0xab, 0x5f, 0x3a, 0x38, 0xef, 0xff, 0x4f,
	0xfd, 0x0f, 0xd0, 0x92, 0xfa, 0x13, 0x0a, 0xf6, 0xc5, 0x1f, 0x78, 0x78, 0x84, 0x81, 0xd7, 0xd0,
	0x92, 0x06, 0x6a, 0x00, 0x65, 0x07, 0xec, 0x2d, 0xd8, 0xd3, 0x20, 0xdc, 0x70, 0xfa, 0xb9, 0xa3,
	0x34, 0x43, 0x84, 0x4b, 0x79, 0x54, 0x15, 0x16, 0x57, 0xb1, 0xbc, 0x9b, 0xd3, 0xaf, 0x4c, 0x29,
	0x58, 0x5c, 0xc5, 0xec, 0x15, 0x3c, 0xcd, 0xdb, 0xd2, 0xad, 0x88, 0x53, 0xc2, 0x67, 0x60, 0xce,
	0xd6, 0xaa, 0xab, 0xc9, 0xcd, 0xd9, 0xda, 0xfb, 0x63, 0x82, 0x3d, 0x0c, 0x22, 0xf2, 0x29, 0xd9,
	0x87, 0xdf, 0x09, 0xdf, 0x41, 0xd3, 0xa7, 0x78, 0xa9, 0x78, 0xad, 0xe3, 0x94, 0x35, 0x61, 0xa7,
	0x5d, 0xbe, 0xcc, 0xb1, 0xcc, 0xc0, 0x29, 0xd8, 0xda, 0x1e, 0xe1, 0xcb, 0x63, 0x59, 0xed, 0x2e,
	0x3a, 0xa7, 0x74, 0xed, 0xfe, 0x31, 0x03, 0xc7, 0x00, 0xc5, 0x5a, 0x60, 0x4f, 0xa7, 0x55, 0xd7,
	0xc5, 0xe9, 0xe9, 0xb0, 0x6a, 0x96, 0x19, 0xf8, 0x19, 0x9a, 0xc7, 0x01, 0xa3, 0xa3, 0x93, 0xca,
	0x63, 0x77, 0x1c, 0x9d, 0x53, 0xce, 0x31, 0x03, 0x87, 0x60, 0x9d, 0xa6, 0x84, 0x37, 0x3a, 0xa6,
	0x32, 0x3c, 0xe7, 0x46, 0xe7, 0x54, 0x92, 0xcc, 0xf8, 0x96, 0x7f, 0xef, 0x0f, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xbf, 0x5e, 0x56, 0x81, 0x07, 0x04, 0x00, 0x00,
}
