// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_20.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	game_20.proto
	user_10.proto

It has these top-level messages:
	MailRequest
	MailResponse
	Player_Info
	C2S_Login_10001
	S2C_Login_10001
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 请求消息
type MailRequest struct {
	Mail string `protobuf:"bytes,1,opt,name=Mail" json:"Mail,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=Text" json:"Text,omitempty"`
}

func (m *MailRequest) Reset()                    { *m = MailRequest{} }
func (m *MailRequest) String() string            { return proto.CompactTextString(m) }
func (*MailRequest) ProtoMessage()               {}
func (*MailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MailRequest) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *MailRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// 响应消息
type MailResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=Ok" json:"Ok,omitempty"`
}

func (m *MailResponse) Reset()                    { *m = MailResponse{} }
func (m *MailResponse) String() string            { return proto.CompactTextString(m) }
func (*MailResponse) ProtoMessage()               {}
func (*MailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MailResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*MailRequest)(nil), "protos.MailRequest")
	proto.RegisterType((*MailResponse)(nil), "protos.MailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GameService service

type GameServiceClient interface {
	SendMail(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (*MailResponse, error)
}

type gameServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameServiceClient(cc *grpc.ClientConn) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) SendMail(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (*MailResponse, error) {
	out := new(MailResponse)
	err := grpc.Invoke(ctx, "/protos.GameService/SendMail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GameService service

type GameServiceServer interface {
	SendMail(context.Context, *MailRequest) (*MailResponse, error)
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GameService/SendMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).SendMail(ctx, req.(*MailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMail",
			Handler:    _GameService_SendMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game_20.proto",
}

func init() { proto.RegisterFile("game_20.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4f, 0xcc, 0x4d,
	0x8d, 0x37, 0x32, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0xa6,
	0x5c, 0xdc, 0xbe, 0x89, 0x99, 0x39, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c,
	0x2c, 0x20, 0xae, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x0d, 0x12, 0x0b, 0x49, 0xad,
	0x28, 0x91, 0x60, 0x82, 0x88, 0x81, 0xd8, 0x4a, 0x72, 0x5c, 0x3c, 0x10, 0x6d, 0xc5, 0x05, 0xf9,
	0x79, 0xc5, 0xa9, 0x42, 0x7c, 0x5c, 0x4c, 0xfe, 0xd9, 0x60, 0x5d, 0x1c, 0x41, 0x4c, 0xfe, 0xd9,
	0x46, 0x6e, 0x5c, 0xdc, 0xee, 0x89, 0xb9, 0xa9, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42,
	0xe6, 0x5c, 0x1c, 0xc1, 0xa9, 0x79, 0x29, 0x60, 0xe3, 0x84, 0x21, 0x2e, 0x28, 0xd6, 0x43, 0xb2,
	0x57, 0x4a, 0x04, 0x55, 0x10, 0x62, 0xaa, 0x12, 0x43, 0x12, 0xc4, 0x99, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x32, 0x9f, 0xbb, 0xc1, 0xbe, 0x00, 0x00, 0x00,
}
