// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_10.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Player_Info struct {
	Uid       int64  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	AccountId int64  `protobuf:"varint,2,opt,name=accountId" json:"accountId,omitempty"`
	Nick      string `protobuf:"bytes,3,opt,name=nick" json:"nick,omitempty"`
	Level     int32  `protobuf:"varint,4,opt,name=level" json:"level,omitempty"`
	Coin      int64  `protobuf:"varint,5,opt,name=coin" json:"coin,omitempty"`
	Diamond   int64  `protobuf:"varint,6,opt,name=diamond" json:"diamond,omitempty"`
	HeadImg   string `protobuf:"bytes,7,opt,name=headImg" json:"headImg,omitempty"`
}

func (m *Player_Info) Reset()                    { *m = Player_Info{} }
func (m *Player_Info) String() string            { return proto.CompactTextString(m) }
func (*Player_Info) ProtoMessage()               {}
func (*Player_Info) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Player_Info) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Player_Info) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Player_Info) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *Player_Info) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Player_Info) GetCoin() int64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *Player_Info) GetDiamond() int64 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *Player_Info) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

type C2S_Login_10001 struct {
	Token     string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	AccountId int64  `protobuf:"varint,2,opt,name=accountId" json:"accountId,omitempty"`
}

func (m *C2S_Login_10001) Reset()                    { *m = C2S_Login_10001{} }
func (m *C2S_Login_10001) String() string            { return proto.CompactTextString(m) }
func (*C2S_Login_10001) ProtoMessage()               {}
func (*C2S_Login_10001) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *C2S_Login_10001) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *C2S_Login_10001) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type S2C_Login_10001 struct {
	Code int32        `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Info *Player_Info `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *S2C_Login_10001) Reset()                    { *m = S2C_Login_10001{} }
func (m *S2C_Login_10001) String() string            { return proto.CompactTextString(m) }
func (*S2C_Login_10001) ProtoMessage()               {}
func (*S2C_Login_10001) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *S2C_Login_10001) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *S2C_Login_10001) GetInfo() *Player_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*Player_Info)(nil), "protos.Player_Info")
	proto.RegisterType((*C2S_Login_10001)(nil), "protos.C2S_Login_10001")
	proto.RegisterType((*S2C_Login_10001)(nil), "protos.S2C_Login_10001")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	Login(ctx context.Context, in *C2S_Login_10001, opts ...grpc.CallOption) (*S2C_Login_10001, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *C2S_Login_10001, opts ...grpc.CallOption) (*S2C_Login_10001, error) {
	out := new(S2C_Login_10001)
	err := grpc.Invoke(ctx, "/protos.UserService/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	Login(context.Context, *C2S_Login_10001) (*S2C_Login_10001, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2S_Login_10001)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*C2S_Login_10001))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_10.proto",
}

func init() { proto.RegisterFile("user_10.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x26, 0x69, 0xc9, 0x04, 0xa9, 0xac, 0x82, 0x8b, 0x78, 0x08, 0xb9, 0x98, 0x53, 0x49,
	0xe2, 0xd1, 0x63, 0xf1, 0x10, 0x11, 0x91, 0x0d, 0x9e, 0x43, 0xcc, 0x4e, 0xeb, 0xd2, 0x74, 0x57,
	0xf2, 0x51, 0xf0, 0x57, 0xf9, 0x17, 0x25, 0x13, 0xe2, 0x47, 0x0f, 0x3d, 0xed, 0x7b, 0x6f, 0x66,
	0xde, 0x3e, 0x66, 0xe0, 0xac, 0x6f, 0xb1, 0x29, 0x92, 0x78, 0xf9, 0xd1, 0x98, 0xce, 0xb0, 0x19,
	0x3d, 0x6d, 0xf8, 0x65, 0x81, 0xff, 0x52, 0x97, 0x9f, 0xd8, 0x14, 0x99, 0x5e, 0x1b, 0x76, 0x0e,
	0x76, 0xaf, 0x24, 0xb7, 0x02, 0x2b, 0xb2, 0xc5, 0x00, 0xd9, 0x0d, 0x78, 0x65, 0x55, 0x99, 0x5e,
	0x77, 0x99, 0xe4, 0xa7, 0xa4, 0xff, 0x0a, 0x8c, 0x81, 0xa3, 0x55, 0xb5, 0xe5, 0x76, 0x60, 0x45,
	0x9e, 0x20, 0xcc, 0x2e, 0xc1, 0xad, 0x71, 0x8f, 0x35, 0x77, 0x02, 0x2b, 0x72, 0xc5, 0x48, 0x86,
	0xce, 0xca, 0x28, 0xcd, 0x5d, 0xb2, 0x20, 0xcc, 0x38, 0xcc, 0xa5, 0x2a, 0x77, 0x46, 0x4b, 0x3e,
	0x23, 0x79, 0xa2, 0x43, 0xe5, 0x1d, 0x4b, 0x99, 0xed, 0x36, 0x7c, 0x4e, 0xd6, 0x13, 0x0d, 0x1f,
	0x60, 0xb1, 0x4a, 0xf3, 0xe2, 0xc9, 0x6c, 0x94, 0x2e, 0x92, 0x38, 0x8e, 0x93, 0xe1, 0xc3, 0xce,
	0x6c, 0x51, 0x53, 0x6c, 0x4f, 0x8c, 0xe4, 0x78, 0xf0, 0xf0, 0x19, 0x16, 0x79, 0xba, 0xfa, 0x67,
	0x43, 0x09, 0x25, 0x92, 0x8b, 0x2b, 0x08, 0xb3, 0x5b, 0x70, 0x94, 0x5e, 0x1b, 0x9a, 0xf7, 0xd3,
	0x8b, 0x71, 0x7b, 0xed, 0xf2, 0xcf, 0xca, 0x04, 0x35, 0xa4, 0x8f, 0xe0, 0xbf, 0xb6, 0xd8, 0xe4,
	0xd8, 0xec, 0x55, 0x85, 0xec, 0x1e, 0x5c, 0xb2, 0x66, 0x57, 0xd3, 0xc8, 0x41, 0xe8, 0xeb, 0x9f,
	0xc2, 0x41, 0x8c, 0xf0, 0xe4, 0x6d, 0x3c, 0xce, 0xdd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45,
	0xb8, 0x2e, 0x50, 0xb4, 0x01, 0x00, 0x00,
}
